### ISSUE TITLE
Middle click issues in X11

### ISSUE THREAD

**Issue by gnuvince** [sandgorgon/z#1]
When middle clicking in X11, text from the primary buffer is pasted into the editor, thus making B2 actions fail.

**Comment by horvand** [comment]
:+1: (I just downloaded and tried z, and this is definitely an annoying issue)

**Comment by sandgorgon** [comment]
:-) hehehe, okay, I shall work on it.

**Comment by sandgorgon** [comment]
Current investigation of this is that it looks like the actual 'paste' event happens even before the reactions are called in Scala. So it might be a default behavior done before even passing on the mouse event to Java/Scala? If someone has got an idea how to fix it, I'd sure be happy to get help with it.

**Comment by sandgorgon** [comment]
Newest release foregoes use of the B2 (middle-click) and instead it uses B3 to execute commands as well - sort of like a 'context sensitive' B3. Please see the Help screen.

A bit of an experiment on my end :-)
