### ISSUE TITLE
On Win 10 cannot execute dir command.

### ISSUE THREAD

**Issue by vackosar** [sandgorgon/z#14]
I am clicking B3 on dir, but it always responds with an error that program dir was not found. Is there some config needed to load the commands on the path properly?

**Comment by vackosar** [comment]
Executing "cmd /c dir" works.

**Comment by vackosar** [comment]
Relevant: https://stackoverflow.com/questions/24320446/run-shell-commands-in-scala-code-on-windows-seems-to-require-the-full-absolute-p

**Comment by sandgorgon** [comment]
I haven't really worked on the Windows side of things a lot. But for now, I think you need to invoke cmd or some shell as part of your command.

**Comment by vackosar** [comment]
It would be good to have some ability to choose your shell/init command.
