### ISSUE TITLE
Interactive Shell...

### ISSUE THREAD

**Issue by julian-t** [sandgorgon/z#5]
The screenshot shows a shell running in a window, but this isn't interactive (unless I'm doing something wrong). The ability to have a REPL open within z would be great.

**Comment by sandgorgon** [comment]
Hi julian-t,

If you run a shell from a window, you need to run the command 'Input' on the window - so that you can interact with the shell. Please see the command 'Input [regexp]' on the Help Screen. 

Regards.

**Comment by julian-t** [comment]
Hi,

Thanks for your reply. I'm glad that I can do this, but I'm afraid I still
don't quite see how. I've started a shell window with "! /bin/sh" on the
tag line - where and how do I use the Input command in order to (say) run
sbt? I've tried various ideas on the tag line, but none of them seem to
work.

Thanks,

julian

On 7 March 2016 at 12:22, Ramon de Vera Jr. <notifications@github.com>
wrote:

> Hi julian-t,
>
> If you run a shell from a window, you need to run the command 'Input' on
> the window - so that you can interact with the shell. Please see the
> command 'Input [regexp]' on the Help Screen.
>
> Regards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sandgorgon/z/issues/5#issuecomment-193357399>.
>



-- 
Templeman Consulting Limited

**Comment by sandgorgon** [comment]
Hi Julian,

On the tag line you need to set the shell to interactive -   "! /bin/sh -i". When the +Results window comes up, it'll have the prompt come up. From that window's tag line, type "Input" and righ-click on it. That will enable line interpretation. 

So if you enter text right after the prompt and press Enter at the end, the whole line is sent to the shell.

You can see the regexp the code is using to identify that the start of a line has a valid prompt.

But be warned that it won't behave like a terminal - in the end it is just a TextArea that you can send commands to the underlying shell you are running. But it is generally serviceable enough,

The more usual thing to do is actually to just run the command from the tag line.

Commands are execute using the current directory of the window as context. For example, say a window has this prefix on the Tag line -   /home/rdevera/myprojs/z-master, On that window's Tag line, if I type 'sbt assembly', highlight that piece of text, then right-click on it. That will run that command and show you the results on a +Results window in that context. Unfortunately, sbt generates more than plain text log results so you'll see some strange characters with the results - at least that is what is happening with me.

Regards,
Mon

**Comment by sandgorgon** [comment]
Oh, and you may need to enable 'Scroll' too. To make it behave more like you expect.
